// export const ADD_TODOLIST = 'ADD_TODOLIST'
// export const REMOVE_TODOLIST = 'REMOVE_TODOLIST'
// export const CHANGE_FILTER_TODOLIST = 'CHANGE_FILTER_TODOLIST'
// export const CHANGE_TITLE_TODOLIST = 'CHANGE_TITLE_TODOLIST'
// export const REMOVE_TASK = 'REMOVE_TASK'
// export const ADD_TASK = 'ADD_TASK'
// export const CHANGE_STATUS_TASK = 'CHANGE_STATUS_TASK'
// export const CHANGE_TITLE_TASK = 'CHANGE_TITLE_TASK'

export enum ACTIONS_TYPE {
  ADD_TODOLIST = 'ADD_TODOLIST',
  REMOVE_TODOLIST = 'REMOVE_TODOLIST',
  CHANGE_FILTER_TODOLIST = 'CHANGE_FILTER_TODOLIST',
  CHANGE_TITLE_TODOLIST = 'CHANGE_TITLE_TODOLIST',
  REMOVE_TASK = 'REMOVE_TASK',
  ADD_TASK = 'ADD_TASK',
  CHANGE_STATUS_TASK = 'CHANGE_STATUS_TASK',
  CHANGE_TITLE_TASK = 'CHANGE_TITLE_TASK',
}
