
export enum ACTIONS_TYPE {
  ADD_TODOLIST = 'ADD_TODOLIST',
  REMOVE_TODOLIST = 'REMOVE_TODOLIST',
  CHANGE_FILTER_TODOLIST = 'CHANGE_FILTER_TODOLIST',
  CHANGE_TITLE_TODOLIST = 'CHANGE_TITLE_TODOLIST',
  REMOVE_TASK = 'REMOVE_TASK',
  ADD_TASK = 'ADD_TASK',
  CHANGE_STATUS_TASK = 'CHANGE_STATUS_TASK',
  CHANGE_TITLE_TASK = 'CHANGE_TITLE_TASK',
}
