export const ADD_TODOLIST = 'ADD_TODOLIST'
export const REMOVE_TODOLIST = 'REMOVE_TODOLIST'
export const CHANGE_FILTER_TODOLIST = 'CHANGE_FILTER_TODOLIST'
export const CHANGE_TITLE_TODOLIST = 'CHANGE_TITLE_TODOLIST'
